name: crypto_cent
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+5

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cloud_firestore: ^3.4.9
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  firebase_storage: ^10.3.9

  url_launcher: ^6.1.5

  shared_preferences: ^2.0.15
  provider: ^6.0.3

  cached_network_image: ^3.2.2
  cached_video_player: ^2.0.3

  flutter_rating_bar: ^4.0.1

  intl: ^0.17.0

  fluttertoast: ^8.0.9

  currency_picker: ^2.0.11
  intl_phone_field: ^3.1.0

  carousel_slider: ^4.1.1
  scrollable_positioned_list: ^0.3.2
  introduction_screen: ^3.0.2

  pinput: ^2.2.16
  card_swiper: ^2.0.4
  image_picker: ^0.8.6

  qr_flutter: ^4.0.0
  encrypt: ^5.0.1
  location: ^4.4.0
  google_maps_flutter: ^2.2.1
  curved_navigation_bar: ^1.0.3
  change_app_package_name: ^1.1.0
  uuid: ^3.0.7
  fl_chart: ^0.55.2
  google_sign_in: ^5.4.2
  fast_contacts: ^1.1.1
  permission_handler: ^10.2.0
  smooth_page_indicator: ^1.0.0+2
  firebase_messaging: ^13.1.0
  cloud_functions: ^3.3.9
  flutter_local_notifications: ^12.0.4
  flutter_native_timezone: ^2.0.0
  firebase_analytics: ^9.3.8
  video_player: ^2.4.10
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_maps_webservice: ^0.0.19
  flutter_gen: ^5.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  image_path: "assets/logos/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/video/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          weight: 700
          style: italic